# Generated by Django 4.1.1 on 2022-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='query_type',
            field=models.CharField(choices=[('installation', 'Installation'), ('service', 'Service'), ('spares', 'Spares'), ('sales snquiry', 'Sales Enquiry')], max_length=30),
        ),
    ]
