# Generated by Django 4.1.1 on 2022-09-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
