# Generated by Django 4.1.1 on 2022-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='status_of_ticket',
            field=models.CharField(choices=[('telephonic resolution', 'Telephonic Resolution'), ('require spare utilities', 'Require Spare Utilities'), ('payment pending', 'Payment Pending'), ('received by customer', 'Received By Customer'), ('revisit', 'Revisit'), ('resolved', 'Resolved')], max_length=200),
        ),
    ]
