# Generated by Django 4.1.1 on 2022-09-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0002_alter_ticketmodel_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='production_trial_readliness_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
