# Generated by Django 4.1.1 on 2022-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attachments')),
            ],
        ),
    ]
