# Generated by Django 4.1.1 on 2022-09-21 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0003_alter_ticketmodel_production_trial_readliness_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_Creator_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_creator_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
