# Generated by Django 4.1.1 on 2022-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='attachments'),
        ),
    ]
