# Generated by Django 4.1.1 on 2022-09-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvc_app', '0004_alter_ticketmodel_ticket_creator_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_Creator_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_creator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
